"""
coverage_report.py  --  Phase 0, step 4

Produce the Phase 0 coverage/feasibility report (DATA_SPECIFICATION.md Section 7):
qualifying-asset counts per month and per year, coin/token/other breakdown, where
the panel is thin (and which hypotheses that gates), the stablecoin footprint in the
top-N, channel-feasibility notes, rank sensitivity, and the pre-2015 native-coin note.

Inputs:  03_data/universe_panel.csv, universe_assets.csv, classification_table.csv,
        universe_stablecoins_excluded.csv, universe_rank_sensitivity.csv
Output:  03_data/PHASE0_COVERAGE_REPORT.md
"""

from pathlib import Path
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
D = REPO / "03_data"


def main():
    panel = pd.read_csv(D / "universe_panel.csv")
    assets = pd.read_csv(D / "universe_assets.csv")
    cls = pd.read_csv(D / "classification_table.csv")
    sens = pd.read_csv(D / "universe_rank_sensitivity.csv")
    excl = pd.read_csv(D / "universe_stablecoins_excluded.csv")

    panel["year"] = panel["month_end"].str[:4]
    cls_map = cls.set_index("cmc_id")["asset_class"].to_dict()
    panel["asset_class"] = panel["cmc_id"].map(cls_map).fillna("other")
    assets["year"] = assets["entry_month"].str[:4]
    assets["asset_class"] = assets["cmc_id"].map(cls_map).fillna("other")

    obs = panel[panel["status"] == "observed"].copy()
    obs_top250 = obs[obs["mcap_rank"] <= 250]

    # ---- per-month live cross-section ----
    months = sorted(panel["month_end"].unique())
    per_month = []
    for m in months:
        pm = panel[panel["month_end"] == m]
        om = obs[obs["month_end"] == m]
        ot = obs_top250[obs_top250["month_end"] == m]
        per_month.append({
            "month": m,
            "in_panel": len(pm),
            "observed": len(om),
            "obs_top250": len(ot),
            "coins_obs": int((om["asset_class"] == "coin").sum()),
            "tokens_obs": int((om["asset_class"] == "token").sum()),
            "other_obs": int((om["asset_class"] == "other").sum()),
        })
    pm_df = pd.DataFrame(per_month)
    pm_df.to_csv(D / "coverage_by_month.csv", index=False)

    # ---- per-year (use the December snapshot, or last available month of the year) ----
    per_year = []
    for y in sorted(panel["year"].unique()):
        ym = [m for m in months if m.startswith(y)]
        last = ym[-1]
        row = pm_df[pm_df["month"] == last].iloc[0]
        entered = assets[assets["year"] == y]
        per_year.append({
            "year": y, "as_of": last,
            "observed": int(row["observed"]),
            "obs_top250": int(row["obs_top250"]),
            "coins_obs": int(row["coins_obs"]),
            "tokens_obs": int(row["tokens_obs"]),
            "other_obs": int(row["other_obs"]),
            "new_entrants": len(entered),
        })
    py_df = pd.DataFrame(per_year)
    py_df.to_csv(D / "coverage_by_year.csv", index=False)

    # ---- class breakdown: asset count vs observed asset-months ----
    cnt_by_class = assets["asset_class"].value_counts().to_dict()
    obsmonths_by_class = obs["asset_class"].value_counts().to_dict()

    # ---- first month each class has >= 10 observed names (testability gate) ----
    def first_month_with(cls_name, k):
        for m in months:
            n = ((obs["month_end"] == m) & (obs["asset_class"] == cls_name)).sum()
            if n >= k:
                return m
        return "never"

    tok10 = first_month_with("token", 10)
    tok30 = first_month_with("token", 30)
    coin30 = first_month_with("coin", 30)

    # ---- stablecoin footprint in the top-250 over time (illustrative months) ----
    # (excluded from panel; this shows how many top-250 slots they consumed)
    stable_ids = set(cls[cls["asset_class"] == "stablecoin"]["cmc_id"]) | set(excl["cmc_id"])

    nl = "\n"
    lines = []
    A = lines.append
    A("# Phase 0 Coverage & Feasibility Report")
    A("")
    A("**Project:** AFA 2027 QTM Crypto.  **Phase:** 0 (Asset Universe).  "
    "**Generated by:** `04_code/coverage_report.py`.")
    A(f"**Sample:** {months[0]} through {months[-1]} ({len(months)} monthly snapshots, "
    "month-end frequency).")
    A(f"**Primary data source:** CoinMarketCap free historical listings data-api "
    "(point-in-time, includes delisted coins). See `DATA_DECISIONS_LOG.md`.")
    A("")
    A("## 1. Headline counts")
    A("")
    A(f"- **Qualifying assets ever (N=250, ex-stablecoins):** {len(assets)}")
    A(f"- **Live (observed in top-1000) cross-section:** ranges "
    f"{pm_df['observed'].min()}–{pm_df['observed'].max()} assets/month.")
    A(f"- **Observed within top-250 each month:** ranges "
    f"{pm_df['obs_top250'].min()}–{pm_df['obs_top250'].max()} "
    "(short of 250 because excluded stablecoins occupy real top-250 rank slots).")
    A(f"- **Class counts (by distinct asset):** "
    f"coin {cnt_by_class.get('coin',0)}, token {cnt_by_class.get('token',0)}, "
    f"other {cnt_by_class.get('other',0)}.")
    A(f"- **Class weight (by *observed* asset-month, i.e. the live universe):** "
    f"coin {obsmonths_by_class.get('coin',0)}, token {obsmonths_by_class.get('token',0)}, "
    f"other {obsmonths_by_class.get('other',0)}.")
    A(f"- **Stablecoins excluded (hit top-250 at least once):** {len(stable_ids)}.")
    A("")
    A("## 2. Coverage by year (as of each year's last snapshot)")
    A("")
    A("| Year | As of | Observed | Obs≤250 | Coins | Tokens | Other | New entrants |")
    A("|------|-------|----------|---------|-------|--------|-------|--------------|")
    for _, r in py_df.iterrows():
        A(f"| {r['year']} | {r['as_of']} | {r['observed']} | {r['obs_top250']} | "
        f"{r['coins_obs']} | {r['tokens_obs']} | {r['other_obs']} | {r['new_entrants']} |")
    A("")
    A("## 3. Where the panel is thin, and what it gates")
    A("")
    A(f"- **Governance tokens reach ≥10 observed names in {tok10}; ≥30 in {tok30}.** "
    "Before that, H1b / H2 / H3 (which need governance-token cross-sections and "
    "voting data) are not meaningfully testable — the early panel is coin-dominated.")
    A(f"- **Coins reach ≥30 observed names in {coin30}.** H1a (coins) has usable "
    "cross-sectional density from the early sample onward, though 2015–2016 is "
    "still thin and dominated by BTC/LTC/XRP-era assets and many later-failed alts.")
    A("- The 2015–2019 window is coin-heavy and token-sparse exactly as the spec "
    "anticipated; treat early-sample H1b/H2/H3 results as out-of-support.")
    A("")
    A("## 4. The 'other' bucket and classification caveats")
    A("")
    A(f"- {cnt_by_class.get('other',0)} assets ({100*cnt_by_class.get('other',0)/len(assets):.0f}% "
    "of distinct names) are class='other' — oracle/utility/exchange tokens, wrapped/"
    "tokenized assets, memecoins, and the long tail of thin-tagged dead microcaps that "
    "briefly touched the top-250 and were retained per the anti-survivorship rule.")
    A("- Weighted by *observed asset-months* (the live universe), 'other' is a much "
    "smaller share than its raw name-count suggests; the persistent, higher-cap assets "
    "that drive the tests are predominantly classified coin/token.")
    A("- **Classification is a tag-driven first pass and is flagged for review.** CMC "
    "tags are *current* metadata, not point-in-time, so consensus/governance status is "
    "the asset's end-state. Time-varying cases are handled explicitly where known "
    "(ETH: staking from 2020-12-01, full PoS at the 2022-09-15 Merge) and flagged "
    "elsewhere. `ambiguous_flag=True` marks every asset needing manual confirmation "
    f"({int(cls[cls['in_universe']==True]['ambiguous_flag'].sum())} in-universe).")
    A("")
    A("## 5. Stablecoins (excluded from the universe, per project decision)")
    A("")
    A(f"- {len(stable_ids)} stablecoins qualified for the top-250 at least once and were "
    "dropped from the panel so they never enter downstream phases (their ~0 returns and "
    "degenerate λ would otherwise contaminate the cross-section).")
    A("- Ranking was computed *inclusive* of stablecoins so the top-250 cutoff reflects "
    "true market structure; stablecoins were removed only from the output panel. This is "
    "why the observed-top-250 count runs a few-to-low-tens below 250 in later years.")
    A("- Note the cut is functional: TerraUSD (UST) is excluded as a stablecoin, while "
    "LUNA/LUNC (the Terra *coin*) is retained — including its collapse, a deliberate "
    "anti-survivorship inclusion.")
    A("")
    A("## 6. λ-channel feasibility (look-ahead to Phase 1)")
    A("")
    A("- **Staking/locking channel:** available for PoS coins once each chain's staking "
    "launches; absent for pure-PoW coins (no staking) and for ETH before 2020-12. "
    "vote-escrow locked supply (veCRV/veBAL) available for the relevant tokens from "
    "~2020 onward.")
    A("- **Voting-engagement channel:** essentially unavailable before ~2020 and absent "
    "for pure-coin assets; depends on Snapshot/Tally/on-chain governance coverage.")
    A("- **Holding-duration channel:** computable from on-chain data for major chains but "
    "needs per-chain explorer work; the only λ channel realistically available for "
    "early-sample coins.")
    A("")
    A("## 7. Rank-threshold sensitivity (N)")
    A("")
    A("| Top-N | Qualifying total | Non-stablecoin | Stablecoins excluded |")
    A("|-------|------------------|----------------|----------------------|")
    for _, r in sens.iterrows():
        A(f"| {int(r['top_n'])} | {int(r['qualifying_total'])} | "
        f"{int(r['qualifying_non_stablecoin'])} | {int(r['qualifying_stablecoin_excluded'])} |")
    A("")
    A("Default N=250 is used for the panel. The count of qualifying names scales roughly "
    "linearly with N; the live monthly cross-section is what matters for the tests and is "
    "reported above.")
    A("")
    A("## 8. Pre-2015 native-coin extension (supplementary note)")
    A("")
    A("Per spec, no asset's series is extended before 2015-08 in the main panel (common "
    "start for comparability). For a possible coins-only robustness subsample later "
    "(paper Section 5), pre-2015 history exists chiefly for **BTC** (genesis Jan 2009; "
    "CMC price history from ~2013-04), **LTC** (2013), **XRP** (2013), **DOGE** (2013), "
    "and a handful of other 2013–2014 coins. CMC's historical data-api serves snapshots "
    "back to ~2013-04-28, so a BTC-led coins-only sample could be extended ~2.3 years "
    "earlier if needed. This is noted, not built, in Phase 0.")
    A("")
    A("## 9. Open questions for review before Phase 1")
    A("")
    A("1. **Post-delisting months / carry-forward:** assets that fall below rank 1000 are "
    "marked `status='carried_forward'` with last-observed price retained (not dropped). "
    "Phase 3 must decide the death-return treatment (final delisting return vs. constant "
    "carry). Flagged, not resolved, in Phase 0.")
    A("2. **'other'/ambiguous classifications** need a manual confirmation pass for any "
    "asset that will actually enter the tests (i.e. observed, reasonably ranked).")
    A("3. **Confirm N=250** vs. a tighter screen if the live cross-section is judged too "
    "wide once λ-channel coverage is known.")
    A("4. **Artemis** access (paid/auth) if its on-chain fundamentals are wanted for PQ "
    "in Phase 2 — no free API available as of this build.")

    (D / "PHASE0_COVERAGE_REPORT.md").write_text(nl.join(lines), encoding="utf-8")
    print("Wrote PHASE0_COVERAGE_REPORT.md")
    print(py_df.to_string(index=False))


if __name__ == "__main__":
    main()
